
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_center
    hikari:
      username: root
      password: root123
      # >=6.x com.mysql.cj.jdbc.Driver
      # <=5.x com.mysql.cj.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver